# Stage 1: Build Stage
FROM node:20-alpine AS builder

# Set working directory
WORKDIR /app

# Copy package files and install dependencies 
COPY package.json package-lock.json ./
RUN npm install 

# Copy application source code 
COPY . .

# Build the application 
RUN npm run build 

# Stage 2: Production Stage
FROM node:20-alpine

#Set working directory
WORKDIR /app 

# Copy only necessary files from build stage
COPY --from=builder /app/package.json ./
COPY --from=builder /app/package-lock.json ./
COPY --from=builder /app/dist ./dist
COPY --from=builder /app/node_modules ./node_modules

# Expose the application port 
EXPOSE 3000

# Start the application 
CMD ["node", "dist/index.js"]


